package View;

import IO.IO;
import KhoHang.DiaNhac;
import KhoHang.DiaPhim;
import KhoHang.Sach;
import KhoHang.SanPham;
import DoanhThu.SuKien;
import DoanhThu.SuKienMotLan;
import KhoHang.KhoHang;
import java.awt.BorderLayout;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class KhoHangViews extends javax.swing.JFrame {

    private ArrayList<SanPham> listSanPham;
    private ArrayList<SuKienMotLan> listSanPham_SuKien;
    DefaultTableModel model;
    int key = 0;

    IO io = new IO();
    KhoHang khohang = new KhoHang();
    /**
     * Creates new form KhoHangViews
     */
    public KhoHangViews() {
        listSanPham = khohang.getdanhsachsanpham();        
//        listSanPham_SuKien = khohang.getlistSanPham_SuKien();
        listSanPham_SuKien = io.docSKMotLan();
        
        initComponents();
//        this.listSanPham = io.docSP();
        this.setLocationRelativeTo(null);
        this.setLayout(new BorderLayout());
//        listSanPham_SuKien = new ArrayList<>();
        model = (DefaultTableModel) jTable1.getModel();
        TFTenTacGia.setVisible(true);
        TFNhaXuatBan.setVisible(true);
        TFTheLoaiSach.setVisible(true);
        TFNamPhatHanhSach.setVisible(true);
        TFTenCaSi.setVisible(false);
        TFTheLoaiDN.setVisible(false);
        TFNamPhatHanhDN.setVisible(false);
        TFDaoDien.setVisible(false);
        TFDienVien.setVisible(false);
        TFNamSanXuatDP.setVisible(false);
        TFTheLoaiDP.setVisible(false);
        this.showResult();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGrLoai = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        tieudekhohang = new javax.swing.JLabel();
        LabelTen = new javax.swing.JLabel();
        LabelGiaNhap = new javax.swing.JLabel();
        TFTen = new javax.swing.JTextField();
        LabelGiaBan = new javax.swing.JLabel();
        LabelSoLuongNhap1 = new javax.swing.JLabel();
        TFGiaNhap = new javax.swing.JTextField();
        TFSoLuongNhap = new javax.swing.JTextField();
        TFGiaBan = new javax.swing.JTextField();
        LabelTheLoai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnInsert = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        RBtnDiaPhim = new javax.swing.JRadioButton();
        RBtnSach = new javax.swing.JRadioButton();
        RBtnDiaNhac = new javax.swing.JRadioButton();
        PanelLoai = new javax.swing.JPanel();
        TFTenTacGia = new javax.swing.JTextField();
        TFNhaXuatBan = new javax.swing.JTextField();
        TFTenCaSi = new javax.swing.JTextField();
        TFTheLoaiDN = new javax.swing.JTextField();
        TFDaoDien = new javax.swing.JTextField();
        TFDienVien = new javax.swing.JTextField();
        TFTheLoaiSach = new javax.swing.JTextField();
        TFNamPhatHanhDN = new javax.swing.JTextField();
        TFTheLoaiDP = new javax.swing.JTextField();
        TFNamPhatHanhSach = new javax.swing.JTextField();
        TFNamSanXuatDP = new javax.swing.JTextField();
        BtnFull = new javax.swing.JButton();
        Btntim = new javax.swing.JButton();
        Btntimtheoloai = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tieudekhohang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tieudekhohang.setText("THÔNG TIN SẢN PHẨM");

        LabelTen.setText("Tên ");

        LabelGiaNhap.setText("Giá Nhập");

        TFTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTenActionPerformed(evt);
            }
        });

        LabelGiaBan.setText("Giá Bán");

        LabelSoLuongNhap1.setText("Số lượng ");

        TFGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFGiaNhapActionPerformed(evt);
            }
        });

        TFSoLuongNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSoLuongNhapActionPerformed(evt);
            }
        });

        TFGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFGiaBanActionPerformed(evt);
            }
        });

        LabelTheLoai.setText("Thể Loại");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Giá Nhập", "Giá Bán", "Số lượng", "Thể loại"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnInsert.setText("Thêm");
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });

        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        BtnBack.setText("Trở Về");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnGrLoai.add(RBtnDiaPhim);
        RBtnDiaPhim.setText("Đĩa phim");
        RBtnDiaPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnDiaPhimActionPerformed(evt);
            }
        });

        BtnGrLoai.add(RBtnSach);
        RBtnSach.setSelected(true);
        RBtnSach.setText("Sách");
        RBtnSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnSachActionPerformed(evt);
            }
        });

        BtnGrLoai.add(RBtnDiaNhac);
        RBtnDiaNhac.setText("Đĩa nhạc");
        RBtnDiaNhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnDiaNhacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoaiLayout = new javax.swing.GroupLayout(PanelLoai);
        PanelLoai.setLayout(PanelLoaiLayout);
        PanelLoaiLayout.setHorizontalGroup(
            PanelLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelLoaiLayout.setVerticalGroup(
            PanelLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TFTenTacGia.setText("Tác giả");
        TFTenTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFTenTacGiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFTenTacGiaMouseExited(evt);
            }
        });
        TFTenTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTenTacGiaActionPerformed(evt);
            }
        });

        TFNhaXuatBan.setText("Nhà xuất bản");
        TFNhaXuatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFNhaXuatBanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFNhaXuatBanMouseExited(evt);
            }
        });

        TFTenCaSi.setText("Ca sĩ");
        TFTenCaSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFTenCaSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFTenCaSiMouseExited(evt);
            }
        });

        TFTheLoaiDN.setText("Thể Loại");
        TFTheLoaiDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFTheLoaiDNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFTheLoaiDNMouseExited(evt);
            }
        });

        TFDaoDien.setText("Đạo Diễn");
        TFDaoDien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFDaoDienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFDaoDienMouseExited(evt);
            }
        });
        TFDaoDien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDaoDienActionPerformed(evt);
            }
        });

        TFDienVien.setText("Diễn Viên");
        TFDienVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFDienVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFDienVienMouseExited(evt);
            }
        });

        TFTheLoaiSach.setText("Thể Loại");
        TFTheLoaiSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFTheLoaiSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFTheLoaiSachMouseExited(evt);
            }
        });

        TFNamPhatHanhDN.setText("Năm phát hành");
        TFNamPhatHanhDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFNamPhatHanhDNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFNamPhatHanhDNMouseExited(evt);
            }
        });

        TFTheLoaiDP.setText("Thể loại");
        TFTheLoaiDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFTheLoaiDPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFTheLoaiDPMouseExited(evt);
            }
        });

        TFNamPhatHanhSach.setText("Năm phát hành");
        TFNamPhatHanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFNamPhatHanhSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFNamPhatHanhSachMouseExited(evt);
            }
        });

        TFNamSanXuatDP.setText("Năm sản xuất");
        TFNamSanXuatDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFNamSanXuatDPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TFNamSanXuatDPMouseExited(evt);
            }
        });

        BtnFull.setText("Full");
        BtnFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFullActionPerformed(evt);
            }
        });

        Btntim.setText("Tìm");
        Btntim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtntimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtntimMouseExited(evt);
            }
        });
        Btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntimActionPerformed(evt);
            }
        });

        Btntimtheoloai.setText("Tìm theo loại");
        Btntimtheoloai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtntimtheoloaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtntimtheoloaiMouseExited(evt);
            }
        });
        Btntimtheoloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntimtheoloaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BtnInsert)
                        .addGap(18, 18, 18)
                        .addComponent(BtnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnFull)
                        .addGap(18, 18, 18)
                        .addComponent(Btntim))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PanelLoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LabelGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TFGiaNhap))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LabelTen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TFTen))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LabelGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TFGiaBan))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LabelSoLuongNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TFSoLuongNhap))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(LabelTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                                    .addComponent(RBtnSach, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(TFNamPhatHanhSach)
                                                        .addComponent(TFTheLoaiSach)
                                                        .addComponent(TFNhaXuatBan)
                                                        .addComponent(TFTenTacGia))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(RBtnDiaNhac)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(RBtnDiaPhim))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TFNamPhatHanhDN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TFTheLoaiDN)
                                                        .addComponent(TFTenCaSi))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(TFDaoDien)
                                                        .addComponent(TFDienVien)
                                                        .addComponent(TFNamSanXuatDP)
                                                        .addComponent(TFTheLoaiDP))))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(tieudekhohang)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(Btntimtheoloai, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tieudekhohang)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelSoLuongNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBtnSach)
                            .addComponent(RBtnDiaNhac)
                            .addComponent(RBtnDiaPhim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFTenCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFDaoDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFTheLoaiDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFDienVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFTheLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFNamPhatHanhDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFTheLoaiDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFNamPhatHanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFNamSanXuatDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(PanelLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnClear)
                    .addComponent(BtnFull)
                    .addComponent(Btntim)
                    .addComponent(BtnInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btntimtheoloai)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTenActionPerformed

    private void TFGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFGiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFGiaNhapActionPerformed

    private void TFSoLuongNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSoLuongNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSoLuongNhapActionPerformed

    private void TFGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFGiaBanActionPerformed

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        // TODO add your handling code here:

        SanPham sp = null;
        for (int i = 0; i < listSanPham.size(); i++) {
            if (listSanPham.get(i).getTensanpham().equals(TFTen.getText())) {
                sp = listSanPham.get(i);
                sp.setSoLuong(sp.getSoluong() + Integer.parseInt(TFSoLuongNhap.getText()));
                key = 1;
                break;
            }
        }
        if (key == 0) {
//            sp = new SanPham(TFTen.getText(),Integer. parseInt(TFGiaNhap.getText()),Integer. parseInt(TFGiaBan.getText()));
            if (RBtnSach.isSelected()) {
                sp = new Sach();
                sp.setTensanpham(TFTen.getText());
                sp.setGianhap(Integer.parseInt(TFGiaNhap.getText()));
                sp.setGiaban(Integer.parseInt(TFGiaBan.getText()));
                sp.setSoLuong(Integer.parseInt(TFSoLuongNhap.getText()));
                ((Sach) sp).setTentacgia(TFTenTacGia.getText());
                ((Sach) sp).setNhaxuatban(TFNhaXuatBan.getText());
                ((Sach) sp).setTheloai(TFTheLoaiSach.getText());
                ((Sach) sp).setNamphathanh(Integer.parseInt(TFNamPhatHanhSach.getText()));
            } else if (RBtnDiaNhac.isSelected()) {
                sp = new DiaNhac();
                sp.setTensanpham(TFTen.getText());
                sp.setGianhap(Integer.parseInt(TFGiaNhap.getText()));
                sp.setGiaban(Integer.parseInt(TFGiaBan.getText()));
                sp.setSoLuong(Integer.parseInt(TFSoLuongNhap.getText()));
                ((DiaNhac) sp).setTencasi(TFTenCaSi.getText());
                ((DiaNhac) sp).setTheloai(TFTheLoaiDN.getText());
                ((DiaNhac) sp).setNamphathanh(Integer.parseInt(TFNamPhatHanhDN.getText()));
            } else if (RBtnDiaPhim.isSelected()) {
                sp = new DiaPhim();
                sp.setTensanpham(TFTen.getText());
                sp.setGianhap(Integer.parseInt(TFGiaNhap.getText()));
                sp.setGiaban(Integer.parseInt(TFGiaBan.getText()));
                sp.setSoLuong(Integer.parseInt(TFSoLuongNhap.getText()));
                ((DiaPhim) sp).setDaodien(TFDaoDien.getText());
                ((DiaPhim) sp).setDienvien(TFDienVien.getText());
                ((DiaPhim) sp).setTheloai(TFTheLoaiDP.getText());
                ((DiaPhim) sp).setNamsanxuat(Integer.parseInt(TFNamSanXuatDP.getText()));
            }
            listSanPham.add(sp);
            System.out.print(listSanPham);
        }
        key = 0;
        Date ngay = new Date();
//        SuKienMotLan sk = new SuKienMotLan(sp, ngay, "mua", Integer.parseInt(TFSoLuongNhap.getText()));
//        sk.isRealSK();
//        listSanPham_SuKien.add(sk);
        showResult(); /// Bảng hiện thêm hàng do hàm showResult này còn danh sách listSanPham vẫn chỉ có các sản phẩm ko cùng tên
        io.ghiSP(listSanPham);
//<<<<<<< HEAD
        listSanPham_SuKien.add(new SuKienMotLan(LocalDateTime.now(), "Nhập " + sp.getTensanpham(), "Mua", sp.getGianhap() * Integer.parseInt(TFSoLuongNhap.getText())));

//=======
//>>>>>>> 54ece6ad40efb32609cb22d70a07da9dd75cef56
        io.ghiSKMotLan(listSanPham_SuKien);

    }//GEN-LAST:event_BtnInsertActionPerformed
    private void setstatusBTNGR(){
        RBtnDiaNhac.setVisible(true);
        RBtnDiaPhim.setVisible(true);
        RBtnSach.setVisible(true);
        if (RBtnSach.isSelected()) {
                TFTenTacGia.setVisible(true);
            TFNhaXuatBan.setVisible(true);
            TFTheLoaiSach.setVisible(true);
            TFNamPhatHanhSach.setVisible(true);

            TFTenCaSi.setVisible(false);
            TFTheLoaiDN.setVisible(false);
            TFNamPhatHanhDN.setVisible(false);

            TFDaoDien.setVisible(false);
            TFDienVien.setVisible(false);
            TFTheLoaiDP.setVisible(false);
            TFNamSanXuatDP.setVisible(false);
        }
        else if (RBtnDiaNhac.isSelected()) {
            TFTenTacGia.setVisible(false);
            TFNhaXuatBan.setVisible(false);
            TFTheLoaiSach.setVisible(false);
            TFNamPhatHanhSach.setVisible(false);

            TFTenCaSi.setVisible(true);
            TFTheLoaiDN.setVisible(true);
            TFNamPhatHanhDN.setVisible(true);

            TFDaoDien.setVisible(false);
            TFDienVien.setVisible(false);
            TFNamSanXuatDP.setVisible(false);
            TFTheLoaiDP.setVisible(false);
        }
        else if (RBtnDiaPhim.isSelected()) {
            TFTenTacGia.setVisible(false);
            TFNhaXuatBan.setVisible(false);
            TFTheLoaiSach.setVisible(false);
            TFNamPhatHanhSach.setVisible(false);

            TFTenCaSi.setVisible(false);
            TFTheLoaiDN.setVisible(false);
            TFNamPhatHanhDN.setVisible(false);

            TFDaoDien.setVisible(true);
            TFDienVien.setVisible(true);
            TFNamSanXuatDP.setVisible(true);
            TFTheLoaiDP.setVisible(true);
        }
    }
    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        JFrame MainViews = new MainViews();
        this.setVisible(false);
        MainViews.setVisible(true);

    }//GEN-LAST:event_BtnBackActionPerformed

    private void RBtnSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnSachActionPerformed
//        PanelLoai.removeAll();
//        PanelLoai.setLayout(new BorderLayout());
//        PanelLoai.add(new SachKhoHang());
//        PanelLoai.validate();
//        PanelLoai.repaint();
        TFTenTacGia.setVisible(true);
        TFNhaXuatBan.setVisible(true);
        TFTheLoaiSach.setVisible(true);
        TFNamPhatHanhSach.setVisible(true);

        TFTenCaSi.setVisible(false);
        TFTheLoaiDN.setVisible(false);
        TFNamPhatHanhDN.setVisible(false);

        TFDaoDien.setVisible(false);
        TFDienVien.setVisible(false);
        TFTheLoaiDP.setVisible(false);
        TFNamSanXuatDP.setVisible(false);


    }//GEN-LAST:event_RBtnSachActionPerformed

    private void RBtnDiaNhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnDiaNhacActionPerformed
        // TODO add your handling code here:
//        PanelLoai.removeAll();
//        PanelLoai.setLayout(new BorderLayout());
//        PanelLoai.add(new DiaNhacKhoHang());
//        PanelLoai.validate();
//        PanelLoai.repaint();
        TFTenTacGia.setVisible(false);
        TFNhaXuatBan.setVisible(false);
        TFTheLoaiSach.setVisible(false);
        TFNamPhatHanhSach.setVisible(false);

        TFTenCaSi.setVisible(true);
        TFTheLoaiDN.setVisible(true);
        TFNamPhatHanhDN.setVisible(true);

        TFDaoDien.setVisible(false);
        TFDienVien.setVisible(false);
        TFNamSanXuatDP.setVisible(false);
        TFTheLoaiDP.setVisible(false);
    }//GEN-LAST:event_RBtnDiaNhacActionPerformed

    private void RBtnDiaPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnDiaPhimActionPerformed
        // TODO add your handling code here:
//        PanelLoai.removeAll();
//        PanelLoai.setLayout(new BorderLayout());
//        PanelLoai.add(new DiaPhimKhoHang());
//        PanelLoai.validate();
//        PanelLoai.repaint();
        TFTenTacGia.setVisible(false);
        TFNhaXuatBan.setVisible(false);
        TFTheLoaiSach.setVisible(false);
        TFNamPhatHanhSach.setVisible(false);

        TFTenCaSi.setVisible(false);
        TFTheLoaiDN.setVisible(false);
        TFNamPhatHanhDN.setVisible(false);

        TFDaoDien.setVisible(true);
        TFDienVien.setVisible(true);
        TFNamSanXuatDP.setVisible(true);
        TFTheLoaiDP.setVisible(true);
    }//GEN-LAST:event_RBtnDiaPhimActionPerformed

    private void TFTenTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTenTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTenTacGiaActionPerformed

    private void TFDaoDienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDaoDienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDaoDienActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFullActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        showResult();
    }//GEN-LAST:event_BtnFullActionPerformed

    private void BtntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntimActionPerformed
        // TODO add your handling code here:
        SanPham sp = null;
        for (int i = 0; i < listSanPham.size(); i++) {
            if (listSanPham.get(i).getTensanpham().equals(TFTen.getText())) {
                sp = listSanPham.get(i);
                break;
            }
        }
        if (sp == null){
            JFrame frame = new JFrame("");
            JOptionPane.showMessageDialog(frame,
                    "Không có sản phẩm",
                    "",
                    JOptionPane.ERROR_MESSAGE);
        }
        model.setRowCount(0);
        model.addRow(new Object[]{
                sp.getTensanpham(), sp.getGianhap(), sp.getGiaban(), sp.getSoluong(), sp.getTheloai()
            });
    }//GEN-LAST:event_BtntimActionPerformed

    private void TFTenTacGiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTenTacGiaMouseEntered
        // TODO add your handling code here:
        TFTenTacGia.setText("");
    }//GEN-LAST:event_TFTenTacGiaMouseEntered

    private void TFTenTacGiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTenTacGiaMouseExited
        // TODO add your handling code here:
        if (TFTenTacGia.getText().equals("")){
            TFTenTacGia.setText("Tác Giả");
        }
    }//GEN-LAST:event_TFTenTacGiaMouseExited

    private void TFNhaXuatBanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNhaXuatBanMouseEntered
        // TODO add your handling code here:
        if (TFNhaXuatBan.getText().equals("Nhà xuất bản")){
            TFNhaXuatBan.setText("");
        }
    }//GEN-LAST:event_TFNhaXuatBanMouseEntered

    private void TFNhaXuatBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNhaXuatBanMouseExited
        // TODO add your handling code here:
        if (TFNhaXuatBan.getText().equals("")){
            TFNhaXuatBan.setText("Nhà Xuất Bản");
        }
    }//GEN-LAST:event_TFNhaXuatBanMouseExited

    private void TFTheLoaiSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTheLoaiSachMouseEntered
        // TODO add your handling code here:
        if (TFTheLoaiSach.getText().equals("Thể Loại")){
            TFTheLoaiSach.setText("");
        }
    }//GEN-LAST:event_TFTheLoaiSachMouseEntered

    private void TFTheLoaiSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTheLoaiSachMouseExited
        // TODO add your handling code here:
        if (TFTheLoaiSach.getText().equals("")){
            TFTheLoaiSach.setText("Thể Loại");
        }
    }//GEN-LAST:event_TFTheLoaiSachMouseExited

    private void TFNamPhatHanhSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNamPhatHanhSachMouseEntered
        // TODO add your handling code here:
        if (TFNamPhatHanhSach.getText().equals("Năm Phát Hành")){
            TFNamPhatHanhSach.setText("");
        }
    }//GEN-LAST:event_TFNamPhatHanhSachMouseEntered

    private void TFNamPhatHanhSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNamPhatHanhSachMouseExited
        // TODO add your handling code here:
        if (TFNamPhatHanhSach.getText().equals("")){
            TFNamPhatHanhSach.setText("Năm Phát Hành");
        }
    }//GEN-LAST:event_TFNamPhatHanhSachMouseExited

    private void TFTenCaSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTenCaSiMouseEntered
        // TODO add your handling code here:
        TFTenCaSi.setText("");
    }//GEN-LAST:event_TFTenCaSiMouseEntered

    private void TFTenCaSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTenCaSiMouseExited
        // TODO add your handling code here:
        if (TFTenCaSi.getText().equals("")){
            TFTenCaSi.setText("Ca Sĩ");
        }
    }//GEN-LAST:event_TFTenCaSiMouseExited

    private void TFTheLoaiDNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTheLoaiDNMouseEntered
        // TODO add your handling code here:
        TFTheLoaiDN.setText("");
        
    }//GEN-LAST:event_TFTheLoaiDNMouseEntered

    private void TFTheLoaiDNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTheLoaiDNMouseExited
        // TODO add your handling code here:
        if (TFTheLoaiDN.getText().equals("")){
            TFTheLoaiDN.setText("Thể Loại");
        }
    }//GEN-LAST:event_TFTheLoaiDNMouseExited

    private void TFNamPhatHanhDNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNamPhatHanhDNMouseEntered
        // TODO add your handling code here:
        TFNamPhatHanhDN.setText("");
    }//GEN-LAST:event_TFNamPhatHanhDNMouseEntered

    private void TFNamPhatHanhDNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNamPhatHanhDNMouseExited
        // TODO add your handling code here:
        if (TFNamPhatHanhDN.getText().equals("")){
            TFNamPhatHanhDN.setText("Năm Phát Hành");
        }
    }//GEN-LAST:event_TFNamPhatHanhDNMouseExited

    private void TFDaoDienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFDaoDienMouseEntered
        // TODO add your handling code here:
         TFDaoDien.setText("");
    }//GEN-LAST:event_TFDaoDienMouseEntered

    private void TFDaoDienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFDaoDienMouseExited
        // TODO add your handling code here:
        if (TFDaoDien.getText().equals("")){
            TFDaoDien.setText("Đạo Diễn");
        }
    }//GEN-LAST:event_TFDaoDienMouseExited

    private void TFDienVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFDienVienMouseEntered
        // TODO add your handling code here:
        TFDienVien.setText("");
    }//GEN-LAST:event_TFDienVienMouseEntered

    private void TFDienVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFDienVienMouseExited
        // TODO add your handling code here:
        if (TFDienVien.getText().equals("")){
            TFDienVien.setText("Diễn viên");
        }
    }//GEN-LAST:event_TFDienVienMouseExited

    private void TFTheLoaiDPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTheLoaiDPMouseEntered
        // TODO add your handling code here:
         TFTheLoaiDP.setText("");
    }//GEN-LAST:event_TFTheLoaiDPMouseEntered

    private void TFTheLoaiDPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFTheLoaiDPMouseExited
        // TODO add your handling code here:
        if (TFTheLoaiDP.getText().equals("")){
            TFTheLoaiDP.setText("Thể Loại");
        }
    }//GEN-LAST:event_TFTheLoaiDPMouseExited

    private void TFNamSanXuatDPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNamSanXuatDPMouseEntered
        // TODO add your handling code here:
        TFNamSanXuatDP.setText("");
    }//GEN-LAST:event_TFNamSanXuatDPMouseEntered

    private void TFNamSanXuatDPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNamSanXuatDPMouseExited
        // TODO add your handling code here:
        if (TFNamSanXuatDP.getText().equals("")){
            TFNamSanXuatDP.setText("Năm Sản Xuất");
        }
    }//GEN-LAST:event_TFNamSanXuatDPMouseExited

    private void BtntimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtntimMouseEntered
        // TODO add your handling code here:
        TFTen.setVisible(true);
        TFGiaNhap.setVisible(false);
        TFGiaBan.setVisible(false);
        TFSoLuongNhap.setVisible(false);
        TFTenTacGia.setVisible(false);
        TFNhaXuatBan.setVisible(false);
        TFTheLoaiSach.setVisible(false);
        TFNamPhatHanhSach.setVisible(false);

        TFTenCaSi.setVisible(false);
        TFTheLoaiDN.setVisible(false);
        TFNamPhatHanhDN.setVisible(false);

        TFDaoDien.setVisible(false);
        TFDienVien.setVisible(false);
        TFNamSanXuatDP.setVisible(false);
        TFTheLoaiDP.setVisible(false);
        
        
        RBtnDiaNhac.setVisible(false);
        RBtnDiaPhim.setVisible(false);
        RBtnSach.setVisible(false);
    }//GEN-LAST:event_BtntimMouseEntered

    private void BtntimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtntimMouseExited
        // TODO add your handling code here:
        TFTen.setVisible(true);
        TFGiaNhap.setVisible(true);
        TFGiaBan.setVisible(true);
        TFSoLuongNhap.setVisible(true);
        TFTenTacGia.setVisible(true);
        TFNhaXuatBan.setVisible(true);
        TFTheLoaiSach.setVisible(true);
        TFNamPhatHanhSach.setVisible(true);

        TFTenCaSi.setVisible(true);
        TFTheLoaiDN.setVisible(true);
        TFNamPhatHanhDN.setVisible(true);

        TFDaoDien.setVisible(true);
        TFDienVien.setVisible(true);
        TFNamSanXuatDP.setVisible(true);
        TFTheLoaiDP.setVisible(true);
        
        setstatusBTNGR();
    }//GEN-LAST:event_BtntimMouseExited

    private void BtntimtheoloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntimtheoloaiActionPerformed
        // TODO add your handling code here:
        String theloai ;
        if (RBtnSach.isSelected()){
            theloai = "sach";
        }
        else if (RBtnDiaNhac.isSelected()){
            theloai = "dianhac";
        }
        else 
            theloai = "diaphim";
//        System.out.print(theloai);
//        System.out.print(listSanPham.size());
        ArrayList<SanPham> listcantim = khohang.TimTheLoai(theloai, listSanPham);
//        System.out.print(listcantim.size());
        if (listcantim != null){
            model.setRowCount(0);
            for (int i = 0; i < listcantim.size(); i++) {
                SanPham sp = listcantim.get(i);
                model.addRow(new Object[]{
                    sp.getTensanpham(), sp.getGianhap(), sp.getGiaban(), sp.getSoluong(), sp.getTheloai()
                });
            }
        }           
    }//GEN-LAST:event_BtntimtheoloaiActionPerformed

    private void BtntimtheoloaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtntimtheoloaiMouseEntered
        // TODO add your handling code here:
        TFTen.setVisible(false);
        TFGiaNhap.setVisible(false);
        TFGiaBan.setVisible(false);
        TFSoLuongNhap.setVisible(false);
        TFTenTacGia.setVisible(false);
        TFNhaXuatBan.setVisible(false);
        TFTheLoaiSach.setVisible(false);
        TFNamPhatHanhSach.setVisible(false);

        TFTenCaSi.setVisible(false);
        TFTheLoaiDN.setVisible(false);
        TFNamPhatHanhDN.setVisible(false);

        TFDaoDien.setVisible(false);
        TFDienVien.setVisible(false);
        TFNamSanXuatDP.setVisible(false);
        TFTheLoaiDP.setVisible(false);
        
        
        RBtnDiaNhac.setVisible(true);
        RBtnDiaPhim.setVisible(true);
        RBtnSach.setVisible(true);
    }//GEN-LAST:event_BtntimtheoloaiMouseEntered

    private void BtntimtheoloaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtntimtheoloaiMouseExited
        // TODO add your handling code here:
        TFTen.setVisible(true);
        TFGiaNhap.setVisible(true);
        TFGiaBan.setVisible(true);
        TFSoLuongNhap.setVisible(true);
        TFTenTacGia.setVisible(true);
        TFNhaXuatBan.setVisible(true);
        TFTheLoaiSach.setVisible(true);
        TFNamPhatHanhSach.setVisible(true);

        TFTenCaSi.setVisible(true);
        TFTheLoaiDN.setVisible(true);
        TFNamPhatHanhDN.setVisible(true);

        TFDaoDien.setVisible(true);
        TFDienVien.setVisible(true);
        TFNamSanXuatDP.setVisible(true);
        TFTheLoaiDP.setVisible(true);
        
        setstatusBTNGR();
        
    }//GEN-LAST:event_BtntimtheoloaiMouseExited

    private void showResult() {
        model.setRowCount(0);
        for (int i = 0; i < listSanPham.size(); i++) {
            SanPham sp = listSanPham.get(i);
            model.addRow(new Object[]{
                sp.getTensanpham(), sp.getGianhap(), sp.getGiaban(), sp.getSoluong(), sp.getTheloai()
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnFull;
    private javax.swing.ButtonGroup BtnGrLoai;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton Btntim;
    private javax.swing.JButton Btntimtheoloai;
    private javax.swing.JLabel LabelGiaBan;
    private javax.swing.JLabel LabelGiaNhap;
    private javax.swing.JLabel LabelSoLuongNhap1;
    private javax.swing.JLabel LabelTen;
    private javax.swing.JLabel LabelTheLoai;
    private javax.swing.JPanel PanelLoai;
    private javax.swing.JRadioButton RBtnDiaNhac;
    private javax.swing.JRadioButton RBtnDiaPhim;
    private javax.swing.JRadioButton RBtnSach;
    private javax.swing.JTextField TFDaoDien;
    private javax.swing.JTextField TFDienVien;
    private javax.swing.JTextField TFGiaBan;
    private javax.swing.JTextField TFGiaNhap;
    private javax.swing.JTextField TFNamPhatHanhDN;
    private javax.swing.JTextField TFNamPhatHanhSach;
    private javax.swing.JTextField TFNamSanXuatDP;
    private javax.swing.JTextField TFNhaXuatBan;
    private javax.swing.JTextField TFSoLuongNhap;
    private javax.swing.JTextField TFTen;
    private javax.swing.JTextField TFTenCaSi;
    private javax.swing.JTextField TFTenTacGia;
    private javax.swing.JTextField TFTheLoaiDN;
    private javax.swing.JTextField TFTheLoaiDP;
    private javax.swing.JTextField TFTheLoaiSach;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tieudekhohang;
    // End of variables declaration//GEN-END:variables

}
